name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build for Windows x64
      run: GOOS=linux GOARCH=amd64 go build -v ./... -o bin/janitor_win_x64.exe
      
    - name: Build for Darwin ARM
      run: GOOS=darwin GOARCH=arm go build -v ./... -o bin/janitor_darwin_arm

